### ISSUE TITLE
Version 1.1: Windows Taskbar gets excluded from the dimming area. Issue persists when run as Admin.

### ISSUE THREAD

**Issue by pranay6481** [jaywick/DimScreen#3]
![screenshot 2](https://cloud.githubusercontent.com/assets/8765418/4263118/d4ef855e-3bcc-11e4-836b-3cec00a2a54c.png)

**Comment by pointyointment** [comment]
[This program](http://www.donationcoder.com/Software/Skrommel/index.html#DimScreen) with the exact same name does it. It still doesn't dim the cursor, menus, tooltips, etc., though. And Alt-Tab makes the whole screen bright.

**Comment by jaywick** [comment]
Thanks for that link @pointyointment. Looks like we can play with the [source AHK](http://www.donationcoder.com/Software/Skrommel/DimScreen/DimScreen.ahk) and try make Alt Tab work. Worth having a look for anyone else who ends up here :grinning:
