### ISSUE TITLE
TaskBar is not dimness out on Windows 7

### ISSUE THREAD

**Issue by r57zone** [jaywick/DimScreen#6]
TaskBar is not dimness out on Windows 7

**Comment by Aelavin** [comment]
I changed code a little bit to fix this isssue. It was especially annoying in fullscreen mode (Twitch.tv, YouTube). Send me a message if you want fixed program.

**Comment by r57zone** [comment]
Yes I would like to.

**Comment by Aelavin** [comment]
You can download app under this link:
https://drive.google.com/open?id=0ByIGXlBpjvyDaFpTUVdyQ1JhVUU

**Comment by r57zone** [comment]
The problem is still present.

**Comment by Aelavin** [comment]
Damn. I've got Windows 10 and it's working quite nice. Unfortunately I don't have Windows 7 on any of my computers :/ I'll try to find some solution if it's possible.

**Comment by Aelavin** [comment]
Okay, I changed program. It should work now. You can download fixed program from same link (replaced old program with new one).

**Comment by Aelavin** [comment]
Okay, I've changed program. Now it should work. You can download fixed program from same link as before (replaced old program with new one).

**Comment by Innomen** [comment]
Thank you :) That did indeed solve the task bar issue. On windows 10 the mouse cursor and right click menu are still normal brightness.

**Comment by Aelavin** [comment]
This program creates transparent overlay application (on top of any other) which can change its background transparency. A mouse cursor and context menus are displayed on top of any application, so this cannot be helped I think.

**Comment by Innomen** [comment]
Ahh ok. Good enough :)

FWIW Flux doesn't have this problem, but it's pretty crappy as just a screen dimming tool.

https://justgetflux.com/

**Comment by Aelavin** [comment]
Maybe people from Flux make it a little bit different (changing color spaces or something like that).
If you find some useful code to make application on top of everything on the desktop then let me know. At least I can try to insert it.
